service:
  name: sender-api

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-s3-local

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, self:custom.defaultStage}
  environment: ${file(./config/environments/${self:provider.stage}.json)}
  iamRoleStatements: ${file(./config/serverless/iam.roles.yaml)}

custom:
  defaultStage: dev
  webpack:
    includeModules: true
  tableName: ${self:provider.environment.DbTableName}
  dbWriteCapacityUnits: ${self:provider.environment.DbWriteCapacityUnits}
  dbReadCapacityUnits: ${self:provider.environment.DbReadCapacityUnits}
  # mock services locally
  s3:
    port: 8000
    directory: /tmp
  dynamodb:
    stages:
      - dev
    start:
      start:
      host: ${self:provider.environment.DB_HOST}
      port: ${self:provider.environment.DB_PORT}
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
  #   seed:
  #     projects:
  #       sources:
  #         - table: ${self:provider.environment.DbTableName}
  #           sources: ['./config/seed/projects.json']

# resources:
#   Resources: ${file(./config/serverless/resources/dynamo.project.table.yaml)}

package:
  excludeDevDependencies: true
  individually: true

functions:
  test2:
    handler: src/functions/test2/test2api.handler
    events:
      - http:
          path: /{version}/test2/{id}
          method: get
          request:
            parameters:
              paths:
                version: true
                id: true
  # project-get:
  #   handler: src/functions/projects/getProject.handler
  #   events:
  #     - http:
  #         path: /projects/{id}
  #         method: get
  #         request:
  #           parameters:
  #             paths:
  #               id: true
  # project-post:
  #   handler: src/functions/projects/createProject.handler
  #   events:
  #     - http:
  #         path: /projects
  #         method: post
  # project-put:
  #   handler: src/functions/projects/updateProject.handler
  #   events:
  #     - http:
  #         path: /projects/{id}
  #         method: put
  #         request:
  #           parameters:
  #             paths:
  #               id: true
  # project-delete:
  #   handler: src/functions/projects/deleteProject.handler
  #   events:
  #     - http:
  #         path: /projects/{id}
  #         method: delete
  #         request:
  #           parameters:
  #             paths:
  #               id: true
  # project-get-all:
  #   handler: src/functions/projects/getAllProject.handler
  #   events:
  #     - http:
  #         path: /projects
  #         method: get
  process-projects-upload:
    handler: src/functions/projects/processProjectsUpload.handler
    events:
      - s3:
          bucket: ${self:provider.environment.PROJECTS_UPLOAD_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
  # mock functions
  # s3-tester:
  #   handler: src/mocks/functions/s3-mock.handler
  #   events:
  #     - http:
  #         path: /mocks/s3-tester
  #         method: GET
